# Generated by Django 4.2.5 on 2024-03-14 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForkliftOwners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('poly', models.CharField(choices=[('1', 'Triangle Polybag B'), ('2', 'Triangle Polybag RJ')], default='1', max_length=2)),
                ('assy', models.CharField(choices=[('1', 'Accumulator'), ('2', 'Scale'), ('3', 'Front Holding Chamber'), ('4', 'Rear Holding Chamber'), ('5', 'Holding Chamber Arm')], default='1', max_length=2)),
                ('unit', models.CharField(choices=[('1', 'Unit 1'), ('2', 'Unit 2'), ('3', 'Unit 3'), ('4', 'Unit 4'), ('5', 'Unit 5'), ('6', 'Unit 6'), ('7', 'Unit 7'), ('8', 'Unit 8'), ('9', 'Unit 9')], default='1', max_length=2)),
            ],
        ),
    ]
