# Generated by Django 4.2.5 on 2024-03-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polybagairactuatorlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForkliftOwners',
            new_name='ActuatorLog',
        ),
    ]
