# Generated by Django 4.2.5 on 2023-11-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.locations'),
        ),
        migrations.DeleteModel(
            name='Equipment_Locations',
        ),
    ]
