# Generated by Django 4.2.5 on 2023-11-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.DeleteModel(
            name='Storage_Locations',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Equipment_brands',
        ),
        migrations.DeleteModel(
            name='Equipment_Locations',
        ),
    ]
