# Generated by Django 4.2.5 on 2023-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage_locations',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
