# Generated by Django 4.2.5 on 2023-10-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_suplumx_alter_storage_locations_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
