# Generated by Django 4.2.5 on 2023-10-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_equipment_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/media/equipment_images/'),
        ),
    ]
