# Generated by Django 4.2.5 on 2023-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_equipment_locations_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_locations',
            name='color',
            field=models.CharField(default='10162d', max_length=10),
        ),
    ]
