# Generated by Django 4.2.5 on 2023-11-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_storage_locations_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupluMX',
        ),
    ]
