# Generated by Django 4.2.5 on 2024-03-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScalesBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('imagen', models.ImageField(null=True, upload_to='scales/brands/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ScalesServiceProviders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('service_description', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(null=True, upload_to='scales/serviceproviders/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ScalesStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('nmax', models.CharField(max_length=255)),
                ('clase', models.CharField(max_length=255)),
                ('powersupply', models.CharField(max_length=255)),
                ('imagen', models.ImageField(null=True, upload_to='scales/equipment/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.scalesbrands')),
                ('service_provider', models.ManyToManyField(blank=True, null=True, to='scales.scalesserviceproviders')),
            ],
        ),
    ]
