# Generated by Django 4.2.5 on 2024-03-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scales',
            old_name='name',
            new_name='clave',
        ),
    ]
