# Generated by Django 4.2.5 on 2024-03-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_rename_name_scales_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='scales',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scales.scalesstatus'),
            preserve_default=False,
        ),
    ]
