# Generated by Django 4.2.5 on 2024-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_scales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scales',
            name='pesomax',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
