# Generated by Django 4.2.5 on 2024-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motors',
            name='enclosure',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motors',
            name='servicefactor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
