# Generated by Django 4.2.5 on 2024-03-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_motors_enclosure_motors_servicefactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motors',
            name='servicefactor',
        ),
    ]
