# Generated by Django 4.2.5 on 2024-02-28 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderInspectionEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladders.ladders')),
                ('usuario', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
