# Generated by Django 4.2.5 on 2024-03-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage'),
        ('ladders', '0002_ladderinspectionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladders',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='storage.locations'),
            preserve_default=False,
        ),
    ]
