# Generated by Django 4.2.5 on 2023-11-21 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkliftBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('imagen', models.ImageField(null=True, upload_to='forklifts/brands/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ForkliftOwners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('service_description', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(null=True, upload_to='forklifts/holders/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ForkliftServiceProviders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
                ('service_description', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(null=True, upload_to='forklifts/serviceproviders/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='ForkliftStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('endusuario', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='end_forklifts', to=settings.AUTH_USER_MODEL)),
                ('startusuario', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='start_forklifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forklifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='forklifts/equipment/')),
                ('clave', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('powered', models.CharField(choices=[('G', 'LPG'), ('E', 'Electric')], max_length=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.forkliftbrands')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.forkliftowners')),
                ('service_provider', models.ManyToManyField(blank=True, null=True, to='forklift.forkliftserviceproviders')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forklift.forkliftstatus')),
            ],
        ),
    ]
