# Generated by Django 4.2.5 on 2023-11-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklifts',
            name='modelo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='forklifts',
            name='serial',
            field=models.CharField(max_length=255),
        ),
    ]
