# Generated by Django 4.2.5 on 2023-11-21 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forklift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loto',
            name='forklift',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forklift.forklifts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loto',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loto',
            name='endusuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='end_forklifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InitialLoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('forklift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.forklifts')),
                ('startusuario', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
