# Generated by Django 4.2.5 on 2023-11-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_alter_forklifts_modelo_alter_forklifts_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forklifts',
            name='color',
        ),
    ]
