# Generated by Django 4.2.5 on 2023-11-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_loto_forklift_alter_loto_end_alter_loto_endusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialloto',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
