# Generated by Django 4.2.5 on 2023-12-02 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forklift', '0003_alter_initialloto_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loto',
            name='endusuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='end_lotos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loto',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loto',
            name='startusuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
