# Generated by Django 4.2.5 on 2023-11-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0003_remove_forklifts_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklifts',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forklift.forkliftstatus'),
            preserve_default=False,
        ),
    ]
