# Generated by Django 4.2.5 on 2023-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0004_alter_loto_endusuario_alter_loto_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklifts',
            name='imagen',
            field=models.ImageField(default='', upload_to='forklifts/equipment/'),
            preserve_default=False,
        ),
    ]
