# Generated by Django 4.2.5 on 2023-11-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0004_forklifts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklifts',
            name='clave',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
