# Generated by Django 4.2.5 on 2023-12-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0005_alter_forklifts_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklifts',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forklift.forkliftstatus'),
        ),
    ]
