# Generated by Django 4.2.5 on 2023-11-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0006_forklifts_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='forkliftowners',
            name='imagen',
            field=models.ImageField(null=True, upload_to='forklifts/brands/banners/'),
        ),
    ]
