# Generated by Django 4.2.5 on 2023-11-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0007_forkliftowners_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftowners',
            name='imagen',
            field=models.ImageField(null=True, upload_to='forklifts/holders/banners/'),
        ),
    ]
