# Generated by Django 4.2.5 on 2023-12-14 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forklift', '0007_waterentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkliftInspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('check1', models.BooleanField()),
                ('check2', models.BooleanField()),
                ('check3', models.BooleanField()),
                ('check4', models.BooleanField()),
                ('check5', models.BooleanField()),
                ('check6', models.BooleanField()),
                ('check7', models.BooleanField()),
                ('check8', models.BooleanField()),
                ('check9', models.BooleanField()),
                ('check10', models.BooleanField()),
                ('check11', models.BooleanField()),
                ('check12', models.BooleanField()),
                ('des1', models.TextField(null=True)),
                ('des2', models.TextField(null=True)),
                ('des3', models.TextField(null=True)),
                ('des4', models.TextField(null=True)),
                ('des5', models.TextField(null=True)),
                ('des6', models.TextField(null=True)),
                ('des7', models.TextField(null=True)),
                ('des8', models.TextField(null=True)),
                ('des9', models.TextField(null=True)),
                ('des10', models.TextField(null=True)),
                ('des11', models.TextField(null=True)),
                ('des12', models.TextField(null=True)),
                ('forklift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.forklifts')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
