# Generated by Django 4.2.5 on 2023-12-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0008_forkliftinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='des9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
