# Generated by Django 4.2.5 on 2023-11-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0009_forkliftbrands_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklifts',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forklift.forkliftserviceproviders'),
        ),
    ]
