# Generated by Django 4.2.5 on 2023-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0011_remove_forklifts_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklifts',
            name='imagen',
            field=models.ImageField(null=True, upload_to='forklifts/equipment/'),
        ),
    ]
