# Generated by Django 4.2.5 on 2024-01-13 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0013_alter_waterentry_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklifts',
            name='batery_target',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forklifts',
            name='last_batery',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
